### ISSUE TITLE
Graph Image

### ISSUE THREAD

**Issue by ceej21** [ZitRos/edu-semantic-knowledge-network-auto-builder#1]
Where does the actual graph image reside?

**Comment by ceej21** [comment]
The HTML Page does not show a graph, rather just lines of words

**Comment by nikitaeverywhere** [comment]
Hi Ceej!

Glad to know you're interested in this thing!

So from what I remember, the output of this program was fed to [Gephi](https://gephi.org/) (you need to additionally install it), and it is Gephi which draws the graph. You should also play a bit with different settings to make it as beautiful as you saw it in the readme file. As a result, you'll be able to plot the graph.

Hope this helps! Let me know.

**Comment by nikitaeverywhere** [comment]
Updated the readme file with this info, thank you! Now closing the issue - should you have any other questions please ask.

Have a great week!
